### ISSUE TITLE
Update dust model  to use latest dust model components

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/lsstdesc-diffsky#26]
The dust model is called or referenced in the following functions that will need to be updated:
[mc_generate_dust_params](https://github.com/LSSTDESC/lsstdesc-diffsky/blob/08f046d9941891ea7f70442fd820b3dcc702c0c7/lsstdesc_diffsky/write_mock_to_disk.py#L1382)
This function generates the dust parameters based on logsm_obs, log_ssfr, redshift and alt_dustpop_params.

Then once these parameters are available, [precompute_dust_attenuation](https://github.com/LSSTDESC/lsstdesc-diffsky/blob/08f046d9941891ea7f70442fd820b3dcc702c0c7/lsstdesc_diffsky/write_mock_to_disk.py#L1391) computes the attenuation factors for whatever filters have been selected. 

Both of these functions will need to be updated to use the new dust model components.

**Comment by aphearin** [comment]
Resolved by #47
