### ISSUE TITLE
Create demo notebook showing how to calculate SEDs from diffsky mocks

### ISSUE THREAD

**Issue by aphearin** [LSSTDESC/lsstdesc-diffsky#6]
Thanks to @jchiang87 for [this starter code](https://github.com/LSSTDESC/lsstdesc-diffsky/commit/afa4184475f86b119d0cdaea3d5ceba8a13b2116).

**Comment by evevkovacs** [comment]
I forgot to tag the issue when I merged in the code that addresses this issue. There are now a couple of notebooks in the Notebooks directory
